services:
  mysql:
    image: 'mysql:latest'
    container_name: airmed_db
    environment:
      - 'MYSQL_DATABASE=airmed'
      - 'MYSQL_PASSWORD=airmed'
      - 'MYSQL_ROOT_PASSWORD=airmed'
      - 'MYSQL_USER=airmed_db'
    ports:
      - "3306:3306"
